name: Auto Update Toolforge

on:
    push:
        branches:
            - main
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
            - name: Deploy on Toolforge
              uses: appleboy/ssh-action@v1.2.4
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  request_pty: true
                  script_stop: true
                  key: ${{ secrets.KEY }}
                  script: |
                      become mdwikicx bash -lc "
                        toolforge-jobs run update --image php8.2 --command ~/shs/update_new_all.sh --wait
                      "
